@extends('layouts.app')

@section('content')
<div class="flex flex-col gap-5">
    <div class="card flex items-center justify-between">
        <div>
            <p class="text-sm text-gray-400">#{{ $employee->employee_id }}</p>
            <h1 class="text-lg font-bold">{{ $employee->employee_name }} — Form Library</h1>
            <p class="text-sm text-gray-400">Archived generated forms for this employee</p>
        </div>
        <button class="px-5 py-2 bg-gray-200 rounded-lg font-bold text-gray-700 text-xs hover:bg-gray-300" onclick="window.history.back()">
            <i class="fa-solid fa-arrow-left mr-1"></i>BACK
        </button>
    </div>

    <div class="card">
        @if($forms->isEmpty())
            <div class="text-sm text-gray-400">No generated forms found yet.</div>
        @else
            <div class="table-container">
                <table>
                    <thead>
                        <tr>
                            <th>TITLE</th>
                            <th>TYPE</th>
                            <th>GENERATED BY</th>
                            <th>DATE</th>
                            <th>ACTION</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($forms as $form)
                            <tr>
                                <td>{{ $form->title }}</td>
                                <td class="uppercase">{{ $form->form_type }}</td>
                                <td>{{ $form->generator?->name ?? 'System' }}</td>
                                <td>{{ $form->created_at->format('m/d/Y h:i A') }}</td>
                                <td>
                                    <a href="{{ route('employees.forms.show', $form) }}" class="px-3 py-1 bg-teal-500 text-white text-xs rounded hover:bg-teal-600 transition">
                                        <i class="fa-solid fa-eye mr-1"></i>VIEW
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        @endif
    </div>
</div>
@endsection
